// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://luigxlpelqcjxklrddjg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1aWd4bHBlbHFjanhrbHJkZGpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MTkwMDYsImV4cCI6MjA1OTE5NTAwNn0.7aLxutlWaLgZn_37XCLFoCEBwSDYBs-MtvI2tozcR4w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);